### ISSUE TITLE
this module does not work under IE6

### ISSUE THREAD

**Issue by francisxia** [leonardfischer/Kohana-Google-Maps-Module#2]
this module is great,however it does not work properly under IE6.

**Comment by leonardfischer** [comment]
I'm sorry to hear that. There were some bugs, which I fixed a few weeks ago - Have you got any ideas what's not working or what is causing the errors? I have no environment to test the IE6 behaviour.

Patches very welcome :)

**Comment by francisxia** [comment]
it's javascript error.it works properly after I removed comma of last array-element.
I am using window7 and I always test IE6 with IETester. 
http://www.my-debugbar.com/wiki/IETester/HomePage
anyway,this module is very cool.I really like it!

**Comment by leonardfischer** [comment]
Mhh, the error you are describing should already be fixed with the actual version. I used "json_encode()" to echo an proper JSON String. Is your version up to date?

I'm not using the IE-Tester because it often shows me some errors, which don't appear in a "real" IE6, but I'm going to try it for the next releases/bugfixes. Thanks - I'm glad you like the module :)
